"""setigen interoperability helpers for screen-based propagation.

These helpers keep the screen models independent from setigen while providing
the two workflows we currently need:

* multiply a setigen ``Frame`` or clean spectrogram signal by a sampled
  scintillation gain field;
* add a scintillated narrowband voltage source to setigen voltage
  ``DataStream``/``Antenna`` objects through their existing callable signal API;
* propagate voltage arrays generated by setigen through the same complex
  transfer machinery used for generic IQ arrays.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Iterable, Optional

import numpy as np
from astropy import units as u
import setigen as stg

from .base_classes import DynamicSpectrum, ElectricFieldSpectrum, NarrowbandToneField
from .voltage import (
    IQPropagationResult,
    field_spectrum_for_baseband,
    propagate_voltage_samples,
)


@dataclass(frozen=True)
class FrameScintillationResult:
    """Result returned after adding or applying scintillation to a Frame."""

    frame: Any
    gain: DynamicSpectrum
    clean_signal: Optional[np.ndarray] = None
    scintillated_signal: Optional[np.ndarray] = None


@dataclass(frozen=True)
class VoltageScintillationResult:
    """Result returned after attaching a scintillated voltage source."""

    source: Any
    streams: tuple[Any, ...]
    signal_functions: tuple[Callable[[np.ndarray], np.ndarray], ...]
    field: NarrowbandToneField


def frame_frequency_axis(frame: Any) -> u.Quantity:
    """Return a setigen Frame frequency axis as an astropy Quantity."""
    return np.asarray(frame.fs, dtype=float) * u.Hz


def frame_time_axis(frame: Any, centers: bool = False) -> u.Quantity:
    """Return a setigen Frame time axis as an astropy Quantity."""
    values = frame.time_centers if centers else frame.ts
    return np.asarray(values, dtype=float) * u.s


def _axis_values(axis: u.Quantity, unit: u.Unit) -> np.ndarray:
    return np.asarray(stg.cast_value(axis, unit).to_value(unit), dtype=float)


def _align_time_values(
    target_times: u.Quantity,
    source_times: u.Quantity,
    time_origin: str,
) -> np.ndarray:
    target = _axis_values(target_times, u.s)
    source = _axis_values(source_times, u.s)
    if len(target) == 0:
        return target
    if time_origin == "start":
        return target - target[0] + source[0]
    if time_origin == "center":
        return target - 0.5 * (target[0] + target[-1]) + 0.5 * (source[0] + source[-1])
    if time_origin == "zero":
        return target
    raise ValueError("time_origin must be 'start', 'center', or 'zero'")


def _prepare_targets(
    target: np.ndarray,
    source: np.ndarray,
    edge_mode: str,
) -> np.ndarray:
    if len(source) == 1:
        return np.full_like(target, source[0], dtype=float)
    lo = float(source[0])
    hi = float(source[-1])
    if edge_mode == "clip":
        return np.clip(target, lo, hi)
    if edge_mode == "wrap":
        period = hi - lo
        if period <= 0:
            return np.clip(target, lo, hi)
        return ((target - lo) % period) + lo
    if edge_mode == "raise":
        if np.any((target < lo) | (target > hi)):
            raise ValueError("target coordinates extend beyond the sampled screen axis")
        return target
    raise ValueError("edge_mode must be 'clip', 'wrap', or 'raise'")


def _interp_vector(
    source_axis: np.ndarray,
    target_axis: np.ndarray,
    values: np.ndarray,
    edge_mode: str,
) -> np.ndarray:
    if len(source_axis) == len(target_axis) and np.allclose(source_axis, target_axis):
        return np.array(values, copy=True)
    if len(source_axis) == 1:
        return np.repeat(values[:1], len(target_axis), axis=0)

    order = np.argsort(source_axis)
    source_axis = source_axis[order]
    values = values[order]
    target_axis = _prepare_targets(target_axis, source_axis, edge_mode)

    flat = values.reshape(len(source_axis), -1)
    out = np.empty((len(target_axis), flat.shape[1]), dtype=values.dtype)
    if np.iscomplexobj(values):
        for idx in range(flat.shape[1]):
            out[:, idx] = (
                np.interp(target_axis, source_axis, flat[:, idx].real)
                + 1j * np.interp(target_axis, source_axis, flat[:, idx].imag)
            )
    else:
        for idx in range(flat.shape[1]):
            out[:, idx] = np.interp(target_axis, source_axis, flat[:, idx])
    return out.reshape((len(target_axis),) + values.shape[1:])


def _interp_axis(
    values: np.ndarray,
    source_axis: u.Quantity,
    target_axis: u.Quantity,
    unit: u.Unit,
    axis: int,
    edge_mode: str,
) -> np.ndarray:
    source = _axis_values(source_axis, unit)
    target = _axis_values(target_axis, unit)
    moved = np.moveaxis(np.asarray(values), axis, 0)
    interpolated = _interp_vector(source, target, moved, edge_mode)
    return np.moveaxis(interpolated, 0, axis)


def _interp_quantity_along_time(
    values: u.Quantity,
    source_times: u.Quantity,
    target_times_aligned: np.ndarray,
    edge_mode: str,
) -> u.Quantity:
    unit = values.unit
    source = _axis_values(source_times, u.s)
    target = _prepare_targets(target_times_aligned, source, edge_mode)
    value_array = np.asarray(values.to_value(unit), dtype=float)
    if len(source) == 1:
        return np.repeat(value_array[:1], len(target)) * unit
    order = np.argsort(source)
    return np.interp(target, source[order], value_array[order]) * unit


def resample_dynamic_spectrum(
    spectrum: DynamicSpectrum,
    *,
    times: u.Quantity | None = None,
    frequencies: u.Quantity | None = None,
    time_origin: str = "start",
    edge_mode: str = "clip",
) -> DynamicSpectrum:
    """Resample a gain dynamic spectrum onto target time/frequency axes."""
    intensity = np.asarray(spectrum.intensity)
    spatial_axis = spectrum.spatial_axis
    time_axis = spectrum.time_axis
    output_frequencies = spectrum.frequencies

    if times is not None:
        if spectrum.time_axis is None:
            raise ValueError("spectrum must have a time_axis to resample onto frame times")
        target_times = stg.cast_value(times, u.s)
        aligned_times = _align_time_values(target_times, spectrum.time_axis, time_origin)
        intensity = _interp_axis(
            intensity,
            spectrum.time_axis,
            aligned_times * u.s,
            u.s,
            axis=0,
            edge_mode=edge_mode,
        )
        spatial_axis = _interp_quantity_along_time(
            spectrum.spatial_axis,
            spectrum.time_axis,
            aligned_times,
            edge_mode=edge_mode,
        )
        time_axis = target_times

    if frequencies is not None:
        output_frequencies = stg.cast_value(frequencies, u.Hz)
        intensity = _interp_axis(
            intensity,
            spectrum.frequencies,
            output_frequencies,
            u.Hz,
            axis=1,
            edge_mode=edge_mode,
        )

    return DynamicSpectrum(
        intensity=intensity,
        frequencies=output_frequencies,
        spatial_axis=spatial_axis,
        time_axis=time_axis,
        metadata={
            **dict(spectrum.metadata),
            "resampled": True,
            "time_origin": time_origin,
            "edge_mode": edge_mode,
        },
    )


def resample_electric_field_spectrum(
    spectrum: ElectricFieldSpectrum,
    *,
    times: u.Quantity | None = None,
    frequencies: u.Quantity | None = None,
    time_origin: str = "start",
    edge_mode: str = "clip",
) -> ElectricFieldSpectrum:
    """Resample a complex field spectrum onto target time/frequency axes."""
    field = np.asarray(spectrum.electric_field)
    spatial_axis = spectrum.spatial_axis
    time_axis = spectrum.time_axis
    output_frequencies = spectrum.frequencies

    if times is not None:
        if spectrum.time_axis is None:
            raise ValueError("spectrum must have a time_axis to resample onto frame times")
        target_times = stg.cast_value(times, u.s)
        aligned_times = _align_time_values(target_times, spectrum.time_axis, time_origin)
        field = _interp_axis(
            field,
            spectrum.time_axis,
            aligned_times * u.s,
            u.s,
            axis=0,
            edge_mode=edge_mode,
        )
        spatial_axis = _interp_quantity_along_time(
            spectrum.spatial_axis,
            spectrum.time_axis,
            aligned_times,
            edge_mode=edge_mode,
        )
        time_axis = target_times

    if frequencies is not None:
        output_frequencies = stg.cast_value(frequencies, u.Hz)
        field = _interp_axis(
            field,
            spectrum.frequencies,
            output_frequencies,
            u.Hz,
            axis=1,
            edge_mode=edge_mode,
        )

    return ElectricFieldSpectrum(
        electric_field=field,
        frequencies=output_frequencies,
        spatial_axis=spatial_axis,
        time_axis=time_axis,
        metadata={
            **dict(spectrum.metadata),
            "resampled": True,
            "time_origin": time_origin,
            "edge_mode": edge_mode,
        },
    )


def screen_field_for_frame(
    model: Any,
    frame: Any,
    *,
    v_trans: u.Quantity,
    normalize: str | None = "mean",
    time_origin: str = "start",
    edge_mode: str = "clip",
    time_centers: bool = False,
    progress: bool = True,
) -> ElectricFieldSpectrum:
    """Sample a screen model's complex field on a setigen Frame grid."""
    if not hasattr(model, "observer_field_spectrum_result"):
        raise TypeError("model must provide observer_field_spectrum_result(frequencies, ...)")
    field = model.observer_field_spectrum_result(
        frame_frequency_axis(frame),
        v_trans=v_trans,
        normalize=normalize,
        progress=progress,
    )
    return resample_electric_field_spectrum(
        field,
        times=frame_time_axis(frame, centers=time_centers),
        frequencies=frame_frequency_axis(frame),
        time_origin=time_origin,
        edge_mode=edge_mode,
    )


def screen_gain_for_frame(
    model: Any,
    frame: Any,
    *,
    v_trans: u.Quantity,
    normalize: str | None = "mean",
    time_origin: str = "start",
    edge_mode: str = "clip",
    time_centers: bool = False,
    progress: bool = True,
) -> DynamicSpectrum:
    """Sample a screen model's intensity gain on a setigen Frame grid."""
    return screen_field_for_frame(
        model,
        frame,
        v_trans=v_trans,
        normalize=normalize,
        time_origin=time_origin,
        edge_mode=edge_mode,
        time_centers=time_centers,
        progress=progress,
    ).as_dynamic_spectrum()


def screen_field_for_voltage(
    model: Any,
    *,
    sample_rate: u.Quantity,
    reference_frequency: u.Quantity,
    v_trans: u.Quantity,
    bandwidth: u.Quantity | None = None,
    frequency_samples: int = 256,
    normalize: str | None = "mean",
    progress: bool = True,
) -> ElectricFieldSpectrum:
    """Sample a screen model for a setigen voltage/baseband span."""
    return field_spectrum_for_baseband(
        model,
        sample_rate=sample_rate,
        center_frequency=reference_frequency,
        v_trans=v_trans,
        bandwidth=bandwidth,
        frequency_samples=frequency_samples,
        normalize=normalize,
        progress=progress,
    )


def propagate_setigen_voltage(
    samples: np.ndarray,
    *,
    model: Any | None = None,
    transfer: ElectricFieldSpectrum | None = None,
    sample_rate: u.Quantity,
    fch1: u.Quantity,
    v_trans: u.Quantity | None = None,
    bandwidth: u.Quantity | None = None,
    frequency_samples: int = 256,
    normalize: str | None = "mean",
    axis: int = -1,
    input_mode: str = "auto",
    output: str = "same",
    block_size: int = 1024,
    hop_size: int | None = None,
    window: str | None = "sqrt_hann",
    ascending: bool = True,
    time_origin: str = "start",
    edge_mode: str = "clip",
    progress: bool = True,
) -> IQPropagationResult:
    """Apply a screen transfer to setigen voltage sample arrays.

    ``samples`` can be a single stream or setigen's usual shaped outputs such
    as ``(1, pol, samples)`` or ``(antenna, pol, samples)``.  Real inputs are
    converted to analytic voltage internally; complex inputs are treated as IQ.
    """
    if transfer is None:
        if model is None or v_trans is None:
            raise ValueError("provide either transfer or both model and v_trans")
        transfer = screen_field_for_voltage(
            model,
            sample_rate=sample_rate,
            reference_frequency=fch1,
            v_trans=v_trans,
            bandwidth=bandwidth,
            frequency_samples=frequency_samples,
            normalize=normalize,
            progress=progress,
        )
    return propagate_voltage_samples(
        samples,
        transfer,
        sample_rate=sample_rate,
        reference_frequency=fch1,
        axis=axis,
        input_mode=input_mode,
        output=output,
        block_size=block_size,
        hop_size=hop_size,
        window=window,
        ascending=ascending,
        time_origin=time_origin,
        edge_mode=edge_mode,
    )


def get_propagated_setigen_voltage(
    source: Any,
    num_samples: int,
    *,
    model: Any | None = None,
    transfer: ElectricFieldSpectrum | None = None,
    v_trans: u.Quantity | None = None,
    bandwidth: u.Quantity | None = None,
    frequency_samples: int = 256,
    normalize: str | None = "mean",
    output: str = "same",
    block_size: int = 1024,
    hop_size: int | None = None,
    window: str | None = "sqrt_hann",
    time_origin: str = "start",
    edge_mode: str = "clip",
    progress: bool = True,
) -> IQPropagationResult:
    """Generate samples from a setigen voltage source, then propagate them."""
    if not hasattr(source, "get_samples"):
        raise TypeError("source must provide get_samples(num_samples)")
    if not all(hasattr(source, attr) for attr in ("sample_rate", "fch1", "ascending")):
        raise TypeError("source must expose sample_rate, fch1, and ascending")
    samples = np.asarray(source.get_samples(int(num_samples)))
    return propagate_setigen_voltage(
        samples,
        model=model,
        transfer=transfer,
        sample_rate=stg.cast_value(source.sample_rate, u.Hz),
        fch1=stg.cast_value(source.fch1, u.Hz),
        v_trans=v_trans,
        bandwidth=bandwidth,
        frequency_samples=frequency_samples,
        normalize=normalize,
        output=output,
        block_size=block_size,
        hop_size=hop_size,
        window=window,
        ascending=source.ascending,
        time_origin=time_origin,
        edge_mode=edge_mode,
        progress=progress,
    )


def _frame_target(frame: Any, in_place: bool) -> Any:
    return frame if in_place else frame.copy()


def _refresh_frame_stats(frame: Any) -> None:
    if hasattr(frame, "_update_noise_frame_stats"):
        frame._update_noise_frame_stats()


def _metadata_for_gain(gain: DynamicSpectrum, operation: str) -> dict[str, Any]:
    return {
        "blscint_scintillation": {
            "operation": operation,
            "gain_shape": tuple(np.shape(gain.intensity)),
            "gain_normalized_mean": float(np.nanmean(gain.intensity)),
            "gain_metadata": dict(gain.metadata),
        }
    }


def _quantity_allclose(left: u.Quantity, right: u.Quantity, unit: u.Unit) -> bool:
    left_values = _axis_values(left, unit)
    right_values = _axis_values(right, unit)
    return left_values.shape == right_values.shape and np.allclose(left_values, right_values)


def _gain_needs_frame_resample(
    gain: DynamicSpectrum,
    frame: Any,
    *,
    time_centers: bool,
) -> bool:
    if np.shape(gain.intensity) != frame.data.shape:
        return True
    if not _quantity_allclose(gain.frequencies, frame_frequency_axis(frame), u.Hz):
        return True
    if gain.time_axis is not None:
        return not _quantity_allclose(gain.time_axis, frame_time_axis(frame, centers=time_centers), u.s)
    return False


def scintillate_frame(
    frame: Any,
    *,
    model: Any | None = None,
    gain: DynamicSpectrum | None = None,
    v_trans: u.Quantity | None = None,
    normalize: str | None = "mean",
    in_place: bool = False,
    time_origin: str = "start",
    edge_mode: str = "clip",
    time_centers: bool = False,
    progress: bool = True,
) -> FrameScintillationResult:
    """Multiply an entire setigen Frame by a screen intensity gain.

    This is the cheapest spectrogram-domain approximation.  It is appropriate
    for a clean signal frame.  If the input frame also contains receiver noise,
    this will scintillate the noise too; use ``add_scintillated_signal`` to
    apply the gain only to a clean signal component before injection.
    """
    if gain is None:
        if model is None or v_trans is None:
            raise ValueError("provide either gain or both model and v_trans")
        gain = screen_gain_for_frame(
            model,
            frame,
            v_trans=v_trans,
            normalize=normalize,
            time_origin=time_origin,
            edge_mode=edge_mode,
            time_centers=time_centers,
            progress=progress,
        )
    elif _gain_needs_frame_resample(gain, frame, time_centers=time_centers):
        gain = resample_dynamic_spectrum(
            gain,
            times=frame_time_axis(frame, centers=time_centers),
            frequencies=frame_frequency_axis(frame),
            time_origin=time_origin,
            edge_mode=edge_mode,
        )

    target = _frame_target(frame, in_place)
    target.data = np.asarray(target.data) * gain.intensity
    _refresh_frame_stats(target)
    if hasattr(target, "add_metadata"):
        target.add_metadata(_metadata_for_gain(gain, "scintillate_frame"))
    return FrameScintillationResult(frame=target, gain=gain)


def render_scintillated_signal(
    frame: Any,
    clean_signal: np.ndarray,
    *,
    model: Any | None = None,
    gain: DynamicSpectrum | None = None,
    v_trans: u.Quantity | None = None,
    normalize: str | None = "mean",
    time_origin: str = "start",
    edge_mode: str = "clip",
    time_centers: bool = False,
    progress: bool = True,
) -> FrameScintillationResult:
    """Return ``clean_signal * gain`` on a setigen Frame grid."""
    clean_signal = np.asarray(clean_signal)
    if clean_signal.shape != frame.data.shape:
        raise ValueError("clean_signal shape must match frame.data shape")

    if gain is None:
        if model is None or v_trans is None:
            raise ValueError("provide either gain or both model and v_trans")
        gain = screen_gain_for_frame(
            model,
            frame,
            v_trans=v_trans,
            normalize=normalize,
            time_origin=time_origin,
            edge_mode=edge_mode,
            time_centers=time_centers,
            progress=progress,
        )
    elif _gain_needs_frame_resample(gain, frame, time_centers=time_centers):
        gain = resample_dynamic_spectrum(
            gain,
            times=frame_time_axis(frame, centers=time_centers),
            frequencies=frame_frequency_axis(frame),
            time_origin=time_origin,
            edge_mode=edge_mode,
        )

    scintillated_signal = clean_signal * gain.intensity
    return FrameScintillationResult(
        frame=frame,
        gain=gain,
        clean_signal=clean_signal,
        scintillated_signal=scintillated_signal,
    )


def add_scintillated_signal(
    frame: Any,
    clean_signal: np.ndarray,
    *,
    model: Any | None = None,
    gain: DynamicSpectrum | None = None,
    v_trans: u.Quantity | None = None,
    normalize: str | None = "mean",
    in_place: bool = True,
    time_origin: str = "start",
    edge_mode: str = "clip",
    time_centers: bool = False,
    progress: bool = True,
) -> FrameScintillationResult:
    """Add a clean spectrogram signal after applying a screen gain."""
    rendered = render_scintillated_signal(
        frame,
        clean_signal,
        model=model,
        gain=gain,
        v_trans=v_trans,
        normalize=normalize,
        time_origin=time_origin,
        edge_mode=edge_mode,
        time_centers=time_centers,
        progress=progress,
    )
    target = _frame_target(frame, in_place)
    target.data = np.asarray(target.data) + rendered.scintillated_signal
    _refresh_frame_stats(target)
    if hasattr(target, "add_metadata"):
        target.add_metadata(_metadata_for_gain(rendered.gain, "add_scintillated_signal"))
    return FrameScintillationResult(
        frame=target,
        gain=rendered.gain,
        clean_signal=rendered.clean_signal,
        scintillated_signal=rendered.scintillated_signal,
    )


def _normalize_tone_field(field: NarrowbandToneField, normalize: str | None) -> NarrowbandToneField:
    if normalize in (None, False, "none"):
        return field
    if normalize == "mean":
        scale = np.nanmean(field.intensity)
    elif normalize == "median":
        scale = np.nanmedian(field.intensity)
    else:
        raise ValueError("normalization mode must be 'mean', 'median', or 'none'")
    if not np.isfinite(scale) or scale == 0:
        raise ValueError("cannot normalize tone field with zero or non-finite intensity scale")
    return NarrowbandToneField(
        electric_field=field.electric_field / np.sqrt(scale),
        frequency=field.frequency,
        spatial_axis=field.spatial_axis,
        time_axis=field.time_axis,
        metadata={**dict(field.metadata), "normalized": normalize},
    )


def sample_tone_envelope(
    field: NarrowbandToneField,
    times: u.Quantity,
    *,
    time_origin: str = "start",
    edge_mode: str = "clip",
) -> np.ndarray:
    """Interpolate a narrowband complex screen envelope at requested times."""
    if field.time_axis is None:
        raise ValueError("field must have a time_axis; pass v_trans when creating it")
    target_times = stg.cast_value(times, u.s)
    aligned_times = _align_time_values(target_times, field.time_axis, time_origin)
    return _interp_axis(
        field.electric_field,
        field.time_axis,
        aligned_times * u.s,
        u.s,
        axis=0,
        edge_mode=edge_mode,
    )


def scintillated_voltage_signal(
    model: Any,
    *,
    f_start: u.Quantity,
    v_trans: u.Quantity,
    level: float,
    drift_rate: u.Quantity = 0 * u.Hz / u.s,
    fch1: u.Quantity = 0 * u.Hz,
    ascending: bool = True,
    phase: float = 0.0,
    normalize: str | None = "mean",
    time_origin: str = "start",
    edge_mode: str = "clip",
    analytic: bool = False,
) -> tuple[Callable[[np.ndarray], np.ndarray], NarrowbandToneField]:
    """Build a setigen-compatible voltage callable for a scintillated tone.

    The callable follows setigen's voltage convention: ``f_start`` is compared
    with the stream's ``fch1`` so the returned samples are in the stream's
    local real-voltage band.  The screen response is sampled at ``f_start``;
    this is the narrowband approximation, so large chirps should be split into
    shorter segments or upgraded to a time-frequency voltage filter later.
    """
    field = _normalize_tone_field(
        model.observer_narrowband_tone_field(f_start, v_trans=v_trans),
        normalize,
    )
    return _voltage_callable_from_field(
        field,
        f_start=f_start,
        level=level,
        drift_rate=drift_rate,
        fch1=fch1,
        ascending=ascending,
        phase=phase,
        time_origin=time_origin,
        edge_mode=edge_mode,
        analytic=analytic,
    ), field


def _voltage_callable_from_field(
    field: NarrowbandToneField,
    *,
    f_start: u.Quantity,
    level: float,
    drift_rate: u.Quantity,
    fch1: u.Quantity,
    ascending: bool,
    phase: float,
    time_origin: str,
    edge_mode: str,
    analytic: bool,
) -> Callable[[np.ndarray], np.ndarray]:
    f0 = stg.cast_value(f_start, u.Hz).to_value(u.Hz)
    stream_fch1 = stg.cast_value(fch1, u.Hz).to_value(u.Hz)
    drift = stg.cast_value(drift_rate, u.Hz / u.s).to_value(u.Hz / u.s)
    level = float(level)
    phase = float(phase)

    def signal_func(ts: np.ndarray) -> np.ndarray:
        times = np.asarray(ts, dtype=float) * u.s
        envelope = sample_tone_envelope(
            field,
            times,
            time_origin=time_origin,
            edge_mode=edge_mode,
        )
        t_values = times.to_value(u.s)
        phase_arg = 2 * np.pi * ((f0 - stream_fch1) * t_values + 0.5 * drift * t_values**2)
        if not ascending:
            phase_arg = -phase_arg
        voltage = level * envelope * np.exp(1j * (phase_arg + phase))
        if analytic:
            return voltage
        return np.real(voltage)

    return signal_func


def _iter_voltage_streams(source: Any) -> Iterable[Any]:
    if hasattr(source, "add_signal") and hasattr(source, "fch1"):
        yield source
        return
    if hasattr(source, "streams"):
        yield from source.streams
        return
    if hasattr(source, "antennas"):
        for antenna in source.antennas:
            yield from antenna.streams
        return
    raise TypeError("source must be a setigen DataStream, Antenna, or MultiAntennaArray")


def add_scintillated_voltage_signal(
    source: Any,
    model: Any,
    *,
    f_start: u.Quantity,
    v_trans: u.Quantity,
    level: float,
    drift_rate: u.Quantity = 0 * u.Hz / u.s,
    phase: float = 0.0,
    normalize: str | None = "mean",
    time_origin: str = "start",
    edge_mode: str = "clip",
    analytic: bool = False,
    polarization_weights: Iterable[float] | None = None,
) -> VoltageScintillationResult:
    """Attach a scintillated narrowband signal to setigen voltage streams.

    ``source`` may be a voltage ``DataStream``, ``Antenna``, or
    ``MultiAntennaArray``.  The same scalar plasma screen envelope is applied
    to each selected stream; magnetoionic/polarization-dependent propagation is
    intentionally outside the current model.
    """
    streams = tuple(_iter_voltage_streams(source))
    if polarization_weights is None:
        weights = np.ones(len(streams))
    else:
        weights = np.asarray(tuple(polarization_weights), dtype=float)
        if len(weights) != len(streams):
            raise ValueError("polarization_weights must match the number of target streams")

    signal_functions = []
    field = _normalize_tone_field(
        model.observer_narrowband_tone_field(f_start, v_trans=v_trans),
        normalize,
    )
    for stream, weight in zip(streams, weights):
        signal_func = _voltage_callable_from_field(
            field,
            f_start=f_start,
            level=float(level) * float(weight),
            drift_rate=drift_rate,
            fch1=stream.fch1 * u.Hz,
            ascending=stream.ascending,
            phase=phase,
            time_origin=time_origin,
            edge_mode=edge_mode,
            analytic=analytic,
        )
        stream.add_signal(signal_func)
        signal_functions.append(signal_func)

    return VoltageScintillationResult(
        source=source,
        streams=streams,
        signal_functions=tuple(signal_functions),
        field=field,
    )


add_scintillated_constant_signal = add_scintillated_voltage_signal
